[program:apache2]
#user = %(ENV_APP_USER)s
command=/usr/sbin/apache2ctl -DFOREGROUND
numprocs=1
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord/apache2-error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stderr_logfile=/var/log/supervisord/apache2-access.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10